// Localization strings for the app
const tr = {
  // Auth screens
  welcome: "Hoş Geldiniz",
  login: "Giriş Yap",
  register: "Kayıt Ol",
  email: "E-posta",
  password: "Şifre",
  confirmPassword: "Şifreyi Onayla",
  forgotPassword: "Şifremi Unuttum",
  resetPassword: "Şifreyi Sıfırla",
  name: "Ad",
  surname: "Soyad",
  username: "Kullanıcı Adı",
  
  // Validation messages
  required: "Bu alan zorunludur",
  invalidEmail: "Geçerli bir e-posta adresi giriniz",
  passwordTooShort: "Şifre en az 6 karakter olmalıdır",
  passwordsDontMatch: "Şifreler eşleşmiyor",
  
  // Home screen
  home: "Ana Sayfa",
  recentLists: "Son Listeler",
  popularLists: "Popüler Listeler",
  viewAll: "Tümünü Gör",
  
  // Lists screen
  lists: "Listelerim",
  myLists: "Listelerim",
  createList: "Liste Oluştur",
  editList: "Listeyi Düzenle",
  deleteList: "Listeyi Sil",
  listName: "Liste Adı",
  listDescription: "Liste Açıklaması",
  wordCount: "Kelime Sayısı",
  noLists: "Henüz liste oluşturmadınız",
  createYourFirstList: "İlk listenizi oluşturun",
  noListsFound: "Liste bulunamadı",
  tryDifferentSearch: "Farklı bir arama yapmayı deneyin",
  createListToStart: "Başlamak için bir liste oluşturun",
  
  // Word screen
  words: "Kelimeler",
  addWord: "Kelime Ekle",
  editWord: "Kelimeyi Düzenle",
  deleteWord: "Kelimeyi Sil",
  word: "Kelime",
  translation: "Çeviri",
  example: "Örnek",
  noWords: "Bu listede henüz kelime yok",
  addYourFirstWord: "İlk kelimenizi ekleyin",
  
  // Learn screen
  learn: "Öğren",
  startLearning: "Öğrenmeye Başla",
  continueLearning: "Öğrenmeye Devam Et",
  reviewWords: "Kelimeleri Gözden Geçir",
  learningMode: "Öğrenme Modu",
  of: "/",
  tapToReveal: "Tanımı görmek için dokunun",
  know: "Biliyorum",
  dontKnow: "Bilmiyorum",
  noWordsToLearn: "Öğrenilecek kelime yok",
  addWordsToLearn: "Öğrenmek için listeye kelimeler ekleyin",
  goBack: "Geri Dön",
  learningCompleted: "Öğrenme Tamamlandı",
  reviewedAllWords: "{0} kelimenin tamamını gözden geçirdiniz",
  mastered: "Öğrenildi",
  learning: "Öğreniliyor",
  total: "Toplam",
  restartLearning: "Tekrar Başlat",
  takeQuiz: "Quiz Yap",
  returnToList: "Listeye Dön",
  loading: "Yükleniyor...",
  
  // Quiz screen
  quiz: "Quiz",
  startQuiz: "Quiz'e Başla",
  continueQuiz: "Quiz'e Devam Et",
  quizResults: "Quiz Sonuçları",
  correctAnswers: "Doğru Cevaplar",
  wrongAnswers: "Yanlış Cevaplar",
  score: "Puan",
  tryAgain: "Tekrar Dene",
  quizMode: "Quiz Modu",
  
  // Progress screen
  progress: "İlerleme",
  wordsLearned: "Öğrenilen Kelimeler",
  quizzesTaken: "Çözülen Quizler",
  averageScore: "Ortalama Puan",
  
  // Settings screen
  settings: "Ayarlar",
  customizeExperience: "Uygulama deneyiminizi özelleştirin",
  account: "Hesap",
  appearance: "Görünüm",
  darkMode: "Karanlık Mod",
  switchTheme: "Aydınlık ve karanlık tema arasında geçiş yapın",
  notifications: "Bildirimler",
  pushNotifications: "Anlık Bildirimler",
  receiveUpdates: "Güncellemeler ve hatırlatıcılar alın",
  sessionReminders: "Oturum Hatırlatıcıları",
  getDailyReminders: "Günlük çalışma hatırlatıcıları alın",
  appPreferences: "Uygulama Tercihleri",
  soundEffects: "Ses Efektleri",
  playSounds: "Uygulama ses efektlerini çal",
  hapticFeedback: "Dokunsal Geri Bildirim",
  vibrationFeedback: "Dokunmatik geri bildirim alın",
  autoSave: "Otomatik Kaydetme",
  autoSaveChanges: "Değişiklikleri otomatik olarak kaydet",
  defaultLanguage: "Varsayılan Dil",
  quizDifficulty: "Quiz Zorluk Seviyesi",
  support: "Destek",
  helpAndSupport: "Yardım ve Destek",
  getHelp: "Sorunlarınız için yardım alın",
  contactUs: "Bize Ulaşın",
  sendFeedback: "Geri bildirim veya öneri gönderin",
  privacyPolicy: "Gizlilik Politikası",
  howWeHandleData: "Verilerinizi nasıl işlediğimiz hakkında bilgi",
  about: "Hakkında",
  appVersion: "Uygulama sürümü ve bilgileri",
  resetSettings: "Ayarları Sıfırla",
  resetSettingsConfirm: "Tüm ayarları varsayılan değerlerine sıfırlamak istediğinizden emin misiniz?",
  logoutConfirm: "Çıkış yapmak istediğinizden emin misiniz?",
  language: "Dil",
  theme: "Tema",
  logout: "Çıkış Yap",
  
  // Common actions
  save: "Kaydet",
  cancel: "İptal",
  delete: "Sil",
  edit: "Düzenle",
  search: "Ara",
  next: "İleri",
  previous: "Geri",
  finish: "Bitir",
  continue: "Devam Et",
  
  // Welcome screen features
  features: {
    createListsTitle: "Kelime Listeleri Oluşturun",
    createListsDesc: "İhtiyacınıza göre özelleştirilmiş kelime listeleri oluşturun",
    learnTitle: "Etkili Öğrenme",
    learnDesc: "Bilimsel yöntemlerle kelimeleri daha hızlı öğrenin",
    quizTitle: "Bilginizi Test Edin",
    quizDesc: "Quizlerle öğrendiğiniz kelimeleri pekiştirin",
    progressTitle: "İlerlemenizi Takip Edin",
    progressDesc: "Öğrenme yolculuğunuzu detaylı istatistiklerle görün"
  },
  
  // Game related
  storyAdventure: "Hikaye Macerası",
  storyMap: "Hikaye Haritası",
  learnThroughStories: "Hikayeler ile öğren",
  featured: "Öne Çıkan",
  play: "Oyna",
  playNow: "ŞİMDİ OYNA",
  chooseDifficulty: "Zorluk Seviyesi Seçin",
  currentDifficulty: "Mevcut Zorluk",
  selected: "Seçili",
  difficulties: {
    easy: "Kolay",
    medium: "Orta",
    hard: "Zor"
  },
  easyDifficultyDesc: "Yeni başlayanlar için ideal",
  mediumDifficultyDesc: "Orta seviye öğrenenler için",
  hardDifficultyDesc: "Kendinizi zorlayın",
  startAdventure: "Maceraya Başla",
  yourStory: "Hikayeniz",
  level: "Seviye",
  completed: "Tamamlandı",
  locked: "Kilitli",
  current: "Mevcut",
  backToMap: "Haritaya Dön",
  nextLevel: "Sonraki Seviye",
  nextChapter: "Sonraki Bölüm",
  finishStory: "Hikayeyi Bitir",
  vocabulary: "Kelime Bilgisi",
  checkYourKnowledge: "Bilginizi Kontrol Edin",
  continueStory: "Hikayeye Devam Et",
  congratulations: "Tebrikler!",
  levelCompleted: "Seviye Tamamlandı!",
  correctAnswer: "Doğru cevap!",
  wrongAnswer: "Yanlış cevap!",
  tryAgain: "Tekrar Dene",
  definition: "Tanım",
  selectTranslation: "Doğru çeviriyi seçin",
  readTheStory: "Hikayeyi Oku",
  testYourKnowledge: "Bilginizi Test Edin",
  selectCorrectTranslations: "Kelime için doğru çeviriyi seçin",
  tapHighlightedWords: "Çevirileri görmek için vurgulanan kelimelere dokunun",
  yourScore: "Puanınız",
  levelNotFound: "Seviye bulunamadı",
  translateWord: "Bu kelimeyi çevir",
  nextQuestion: "Sonraki Soru",
  seeResults: "Sonuçları Gör",
  
  // Door Game
  doorGame: "Kapı Oyunu",
  memorizeWords: "Kelimeleri Ezberleyin",
  chooseDoor: "Doğru Kapıyı Seçin",
  round: "Tur",
  roundOf: "Tur {0}/{1}",
  memorizeTheseWords: "Bu kelimeleri ezberleyin",
  seconds: "saniye",
  selectCorrectDoor: "Doğru çevirisi olan kapıyı seçin",
  correctDoor: "Doğru kapı!",
  wrongDoor: "Yanlış kapı!",
  nextRound: "Sonraki Tur",
  gameOver: "Oyun Bitti",
  finalScore: "Final Puanınız",
  playAgain: "Tekrar Oyna",
  highScore: "En Yüksek Puan",
  newHighScore: "Yeni Rekor!",
  startGame: "Oyuna Başla",
  gameCompleted: "Oyun Tamamlandı!",
  gameCompletedDesc: "Tüm seviyeleri başarıyla tamamladınız",
  timeExpired: "Süre Doldu!",
  
  // Added missing keys for languages
  languages: {
    English: "İngilizce",
    Turkish: "Türkçe",
    Spanish: "İspanyolca",
    French: "Fransızca",
    German: "Almanca",
    Italian: "İtalyanca",
    Russian: "Rusça",
    Chinese: "Çince",
    Japanese: "Japonca",
    Korean: "Korece",
    Arabic: "Arapça"
  },
  
  // Added missing keys for list details
  listDetails: "Liste Detayları",
  createNewList: "Yeni Liste Oluştur",
};

export default tr;